### ISSUE TITLE
udělat skript na gpt2 přes huggingface

### ISSUE THREAD

**Issue by ptakopysk** [ufal/THEaiTRE#15]
theaitre/gpt2_huggingface.py

zatim to běží jen na dll7

**Comment by tuetschek** [comment]
Jako že je hotový?

**Comment by ptakopysk** [comment]
Částečně :-) Na hackatonu jsme to rozchodili v Jupyter notebooku, a ten kód z toho uložili do tohohle skriptu. Teď je potřeba to ještě učesat a přitesat a vstupy výstupy pořešit a tak.

**Comment by tuetschek** [comment]
To zní nadějně 🤓

**Comment by tomasmcz** [comment]
Hotovo.
Kdybyste to chtěli pouštět:
- skript je `gpt2/gpt2.py` , `-h` vypisuje parametry (časem přidám i nastavení parametrů samplování)
- virtuální environment s nainstalovaným torchem je `gpt2/venv-gpt-2`
- pro nastavení CUDAy na klastru sórsujte: `. gpt2/set_cuda_10_1`
- pokud nechcete, aby se vám do houmu stahovalo 7 GB modelu, symlinkujte si z `~/.cache/torch` složku `/net/data/ELITR/gpt/gpt-2/transformers`

**Comment by ptakopysk** [comment]
Zkusil jsem:
`python3 gpt2.py --prompts_dir ../test --out_dir ../testout`

Dostal jsem:
```
INFO:transformers.tokenization_utils:loading file https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-xl-vocab.json from cache at /home/rosa/.cache/torch/transformers/eb2d31fb18c927045d8ccc07cace8bf1c10458bf171a5ad4cb1cbe0b75773425.1512018be4ba4e8726e41b9145129dc30651ea4fec86aa61f4b9f40bf94eac71
INFO:transformers.tokenization_utils:loading file https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-xl-merges.txt from cache at /home/rosa/.cache/torch/transformers/18d7ac53606f670f979f24836b00f5dfee1c58d79bdbcc58411265f194d88ac0.70bec105b4158ed9a1747fea67a43f5dee97855c64d62b6ec3742f4cfdb5feda
Traceback (most recent call last):
  File "/lnet/ms/data/ELITR/gpt/gpt-2/venv-gpt-2/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 541, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/lnet/ms/data/ELITR/gpt/gpt-2/venv-gpt-2/lib/python3.7/site-packages/transformers/tokenization_gpt2.py", line 133, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
PermissionError: [Errno 13] Permission denied: '/home/rosa/.cache/torch/transformers/eb2d31fb18c927045d8ccc07cace8bf1c10458bf171a5ad4cb1cbe0b75773425.1512018be4ba4e8726e41b9145129dc30651ea4fec86aa61f4b9f40bf94eac71'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gpt2.py", line 101, in <module>
    tokenizer, model = setup('gpt2-xl')
  File "gpt2.py", line 17, in setup
    tokenizer = GPT2Tokenizer.from_pretrained(model_name)
  File "/lnet/ms/data/ELITR/gpt/gpt-2/venv-gpt-2/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 390, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/lnet/ms/data/ELITR/gpt/gpt-2/venv-gpt-2/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 544, in _from_pretrained
    "Unable to load vocabulary from file. "
OSError: Unable to load vocabulary from file. Please check that the provided vocabulary is accessible and not corrupted.
```
